### PR TITLE
Fix pagerState

### LINKED ISSUE #871: when go to details it dosen't return to the previous selected tab instead it select the first one always
### What happened?

Once I am on the Plant list tab and click on any item on the list to go to the details screen once I press on back button it returns to the home screen and the selected tab is My Garden instead of the Plant list tab

#### Video to explain the bug 👇🏻 

https://github.com/android/sunflower/assets/30949634/4954d247-d163-4507-967b-90a8ed9d1bdc
 

### 

Part of [GTC](https://www.facebook.com/groups/gazatechcommunity/) open source initiative

### PR DESCRIPTION
**Pull request by devmuhnnad**
This fixes #871 

This pull request addresses the issue of the ``pagerState`` resetting to 1 when navigating back from the plant detail page to the home page in the ``HomeScreen``. The ``pagerState`` is responsible for managing the current page in the home screen pager.

Each time ``HomeScreen`` is recomposed, the pagerState resets

 I have solved the issue by moving the pagerState outside of the HomeScreen composable and making it a remember-composable at a higher level in the composable hierarchy. This way, the ``pagerState`` will be preserved even when the HomeScreen recomposes.
 
 ``PART OF GTC OPEN SOURCE INTIATIVE``

### CODE REVIEW

File: app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt [hunk 1]
```diff
@@ -116,7 +120,9 @@ fun HomePagerScreen(
         modifier = modifier,
         pages = pages,
         gardenPlants = gardenPlants,
-        plants = plants
+        plants = plants,
+            pagerState = pagerState
```
Comment (arriolac) [inline app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt:124]: Nit: Formatting

File: app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt [hunk 2]
```diff
@@ -92,7 +94,8 @@ fun HomeScreen(
             HomePagerScreen(
                 onPlantClick = onPlantClick,
                 onPageChange = onPageChange,
-                plantListViewModel = plantListViewModel
+                plantListViewModel = plantListViewModel,
+                    pagerState = pagerState
```
Comment (arriolac) [inline app/src/main/java/com/google/samples/apps/sunflower/compose/home/HomeScreen.kt:98]: Nit: Formatting

**Review by arriolac — APPROVED** [review]
LGTM just minor formatting issues to address. Thanks for the contribution!

**Comment by devmuhnnad** [comment]
Done!
